application: cat804-instapaper-liker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cron/checkBookmarks
  script: main.app
libraries:
- name: webapp2
  version: "2.5.2"
